title: Open School Bell
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://open-school-bell.github.io/docs/
baseurl: /docs

aux_links:
  GitHub: https://github.com/Open-School-Bell

logo: "/assets/logo.png"
favicon_ico: "/assets/favicon.ico"

repository: open-school-bell/docs

permalink: pretty

callouts:
  warning:
    color: yellow

defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"

gh_edit_link: true 
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/Open-School-Bell/docs" 
gh_edit_branch: "main"
gh_edit_view_mode: "tree"