title: Open School Bell
description: Open School Bell is an open-source solution to provide a modern school bell system.
theme: just-the-docs

url: https://openschoolbell.co.uk
baseurl: /

aux_links:
  GitHub: https://github.com/Open-School-Bell
  X: https://x.com/openschoolbell

logo: "/assets/logo.png"
favicon_ico: "/assets/favicon.ico"

repository: open-school-bell/docs

permalink: pretty

callouts:
  warning:
    color: yellow
  info:
    color: blue

defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "guides"
      type: "pages"
    values:
      layout: "default"

gh_edit_link: true 
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/Open-School-Bell/docs" 
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

heading_anchors: true